### ISSUE TITLE
Avatar not showing up 

### ISSUE THREAD

**Issue by sapphiregirl2** [kartelant/Tupperware#37]
My sister has a tulpa whose avatar refuses to show up

**Comment by kartelant** [comment]
Resolved in 1eb89c413281e1ec6030b98347d1bd7372826a37. Thanks for reporting this, I didn't realize something had changed on Discord's side. Please advise your sister to re-set her tulpa's avatar using the bot - it will clarify the new requirements set by Discord and how to stay within them.
