### ISSUE TITLE
You can register a tulpa to the webhook bot itself

### ISSUE THREAD

**Issue by xSke** [kartelant/Tupperware#4]
If you proxy a "tul!register" command, it's possible to create a tulpa associated with the webhook bot. This tulpa can be edited and managed by anyone with a tulpa registered themselves, as they'll be able to speak through the bot.

This also works for other commands.

**Comment by kartelant** [comment]
Fixed in https://github.com/kartelant/Tupperware/commit/c1ccc961cfdfdca88a819916ef9c2a8470a72dca

**Comment by sapphiregirl2** [comment]
Bot avatar not showing up
