### ISSUE TITLE
NPM install creates error

### ISSUE THREAD

**Issue by AurorahHarmony** [kartelant/Tupperware#6]
When running Npm Install I recieve this error. https://pastebin.com/twDfgn0B
I have tried running the install on Both curremt and LTS versions of Npm, alongside latest stable versions of 4, 6 and 7.

**Comment by Keterr** [comment]
According to https://stackoverflow.com/questions/14772508/npm-failed-to-install-time-with-make-not-found-error if you are running on an Ubuntu system you should try running:
```$ sudo apt-get install build-essential```
to install essential build tools those Node packages attempts to use.

**Comment by AurorahHarmony** [comment]
This seems to have mostly fixed the problem, and all packages install just fine. Thanks
