### ISSUE TITLE
App does not store Tulpa info & Loses it on restart/crash

### ISSUE THREAD

**Issue by AurorahHarmony** [kartelant/Tupperware#7]
I've been testing the app all day, setting it up to run as a service, restart on crash etc with barely any progress. However, I've noticed that through each stop or start, even graceful stops, the bot looses all tulpae data. I've checked the tulpae.json file generated by the bot after creating a new tulpa using `tul!register Aurorah {text}`, and found it to not have any of the data. I feel like this has something to do with the bot not storing information. This happens even when running the app with full root.

**Comment by kartelant** [comment]
Resolved over Discord via a08a27593a255ad656928c0cb0b43ac48071c678
