### ISSUE TITLE
When logging, the logged message is slightly smaller than the real message

### ISSUE THREAD

**Issue by Purrlite** [kartelant/Tupperware#8]
When you enable logging, the bot will print the user's message in the logging channel without the first and last character after removing the brackets, thus removing part of the message. E.g. 
![here](https://user-images.githubusercontent.com/5148235/40575937-bba9c096-60ee-11e8-8948-da4ff8448959.png)

**Comment by kartelant** [comment]
Fixed in 2e56d1855cebfd468e15e01a1e5f796426198baf. Thank you for the bug report! This was a side effect from changing the way messages are sent recently.
